In [281]:
# 1
# Write a one-line code to return the sum of first n numbers  


n = 12     #arbitrarly chosen n = 12 for testing purpose
print((n*(n+1))/2)



78.0


In [283]:
# 2
# Write a short code to multiply a list of numbers with an odd number and print only the even numbers from the resultant list 


l = [3,7,5,4,3,2]        #arbitrarly chosen l value as argument
def mul(l):
    n = int(input("Enter an odd number"))
    if(n%2!=0):
        print("Even numbers are")
        l = [i*n for i in l]
        for j in l:
            if(j%2==0):
                print(j);
                
mul(l)                

Enter an odd number2


In [284]:
# 3
# Write a program to add the corresponding elements of given lists without using a loop 


from operator import add
a=[2,2,2]
b=[3,3,3]

c=list(map(add,a,b))
print(c)

[5, 5, 5]


In [285]:
# 4
# Find number of times the word “slow” is appearing in the following paragraph using Regular Expression: 




import re
txt = "Last year we were hit by a global slow down, but things were looking slowly up from November onwards. Then Coronavirus pandemic hit us in February. The apparel industry has slowed not only in India, but also the world over. We exported in December and January, but the buyers didn’t pay us. Also, there were a lot of cancellations, which didn’t help matters. The apparel sector has a slow turnaround rate and it takes around 90 days to produce garments. So we had a huge stock piling up and compared to other industries we have been hit most severely."
count = re.findall(r'slow\s',txt)
print(len(count))

2


In [288]:
# 5
# Create a 5x5 matrix with random row values ranging from 0 to 4 




import numpy as np
s = np.random.randint(0,4,(5,5))
print(s)

[[3 0 3 3 0]
 [1 1 3 2 3]
 [1 0 3 0 0]
 [3 3 2 1 3]
 [0 1 0 0 2]]


In [291]:
# 6
# Create random vector of size 10 and replace the maximum value by 0 



import random
a=[]
for i in range(1,11):
    a.append(random.random())
print("The vector is",a)

print("Maximum element is = ",max(a))
for j in range(0,10):
    if(a[j]==max(a)):
        a[j]=0
        
print("Resultant vector is ",a)        

The vector is [0.13316921303385987, 0.5473502115649101, 0.14716249413757332, 0.6410931604728051, 0.6325334456182002, 0.1209396461584783, 0.7425750837358048, 0.6526912355080143, 0.22130615023300582, 0.19884236677357414]
Maximum element is =  0.7425750837358048
Resultant vector is  [0.13316921303385987, 0.5473502115649101, 0.14716249413757332, 0.6410931604728051, 0.6325334456182002, 0.1209396461584783, 0, 0, 0.22130615023300582, 0.19884236677357414]


In [292]:
# 7
# Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution 


import numpy as np
mat = np.random.normal(0,1,25)
print(mat)

[ 0.25579934  2.63131843 -0.25020294 -0.8016202   0.56371979  0.66310364
  0.76006976 -1.27103459  0.24308795  0.51810755  0.98353357 -1.21141629
 -0.59276826 -0.39295136 -0.17957484  0.67417026  1.28726398  0.4967217
 -0.61804759  0.95514605  1.32020178 -0.4103573   1.24377535 -0.99396354
  0.87500759]


In [296]:
# 8
# How to find the most frequent value in an array? 



import numpy as np
x = np.random.randint(0,5,10)
print("The array is")
print(x)
print("Most frequent value = ",np.bincount(x).argmax())

The array is
[3 1 2 2 3 4 1 4 1 1]
Most frequent value =  1


In [297]:
# 9
# Create a 5 X 5 matrix using random values and print the matrix and subset – print all values from 3rd Row – 2nd column  till the end 




import numpy as np
s = np.random.randint(0,4,(5,5))
print(s)
print("*************")
print(s[2:,1:])
print(s[3][0])
print(s[4][0])       #I found the question confusing,my apology

[[1 2 2 0 2]
 [2 3 1 2 0]
 [0 2 1 3 0]
 [2 0 3 1 3]
 [3 2 2 2 0]]
*************
[[2 1 3 0]
 [0 3 1 3]
 [2 2 2 0]]
2
3


In [298]:
# 10
#  Create an array with sums of rows and sums of columns in the above matrix




import numpy as np
s = np.random.randint(0,4,(5,5))
print(s)
print("sum of rows = ", np.sum(s, axis = 0))  
print("sum of columns = ", np.sum(s, axis = 1)) 

[[0 1 3 1 3]
 [2 0 2 2 0]
 [1 0 2 3 3]
 [3 3 2 0 1]
 [0 3 1 3 0]]
sum of rows =  [ 6  7 10  9  7]
sum of columns =  [8 6 9 9 7]


In [299]:
# 11
#  Calculate Sum, Average and Standard Deviation of the Matrix created in Q.9 




import numpy as np
s = np.random.randint(0,4,(5,5))
print(s)

print("sum of array=",np.sum(s))
print("Average = ",s.mean())
print("Standard deviation = ",s.std())

[[3 0 2 2 1]
 [1 0 3 3 1]
 [1 1 2 3 3]
 [0 1 0 2 1]
 [2 1 3 2 2]]
sum of array= 40
Average =  1.6
Standard deviation =  1.019803902718557


In [316]:
#12
#Find Average, Standard Deviation of the Total employees, Male employees and female employees separately 




import pandas as pd
data = [['Raju', 'M' , 'Teacher'  ,'English' , 25 , 8000 , 3000 , 11000 ],['Sunil' ,'M' ,'Tester', 'Hindi', 26, 10000 ,12000, 22000 ],['Kiran', 'M', 'Teacher', 'Kannada', 25, 13000, 3000 ,16000 ],['Madhu', 'F', 'Tester' ,'Kannada' ,24 ,12000 ,5000 ,17000 ],['Lakshmi','F', 'Programmer', 'Kannada', 25 ,8000, 7000 ,15000 ],['Pooja','F',' Programmer', 'English', 23 ,9000, 6000 ,15000 ],['Prakash','M','Tester','Hindi', 27, 11000, 4000 ,15000]]
df = pd.DataFrame(data, columns = ['Name' ,'Gender', 'JOB', 'Preferred Language','Age', 'Basic', 'Allowance', 'Total Pay' ]) 
print(df)
print("Average pay of all employees = ",df['Total Pay'].mean())
print("Standard deviation of total pay of all employees = ",df["Total Pay"].std())
q = df.loc[df['Gender'] == "M"]
print("Average Total pay of male employees = ",q['Total Pay'].mean())
print("Standard deviation of Total pay of male employees = ",q['Total Pay'].std())
print(q)
e = df.loc[df['Gender'] == "F"]
print("Average Total pay of female employees = ",e['Total Pay'].mean())
print("Standard deviation of Total pay of female employees = ",e['Total Pay'].std())
e


      Name Gender          JOB Preferred Language  Age  Basic  Allowance  \
0     Raju      M      Teacher            English   25   8000       3000   
1    Sunil      M       Tester              Hindi   26  10000      12000   
2    Kiran      M      Teacher            Kannada   25  13000       3000   
3    Madhu      F       Tester            Kannada   24  12000       5000   
4  Lakshmi      F   Programmer            Kannada   25   8000       7000   
5    Pooja      F   Programmer            English   23   9000       6000   
6  Prakash      M       Tester              Hindi   27  11000       4000   

   Total Pay  
0      11000  
1      22000  
2      16000  
3      17000  
4      15000  
5      15000  
6      15000  
Average pay of all employees =  15857.142857142857
Standard deviation of total pay of all employees =  3287.78402720188
Average Total pay of male employees =  16000.0
Standard deviation of Total pay of male employees =  4546.060565661952
      Name Gender      JOB Prefer

Name Gender          JOB Preferred Language  Age  Basic  Allowance  \
3    Madhu      F       Tester            Kannada   24  12000       5000   
4  Lakshmi      F   Programmer            Kannada   25   8000       7000   
5    Pooja      F   Programmer            English   23   9000       6000   

   Total Pay  
3      17000  
4      15000  
5      15000

In [317]:
# 13
# Find the Top 3 employees with high Total Pay

st = df.sort_values(by='Total Pay',ascending=False)
ds=st[['Name','Total Pay']]
ds.iloc[:3]

Name  Total Pay
1  Sunil      22000
3  Madhu      17000
2  Kiran      16000

In [318]:
#  14
# Find the most common Job and most common language 


u=df[['JOB','Preferred Language']]
print(u.mode())

      JOB Preferred Language
0  Tester            Kannada


In [319]:
#15
# Find the employee whose basic pay is 9000


ty=df[['Name','Basic']]
print(ty.loc[df['Basic'] == 9000])

    Name  Basic
5  Pooja   9000


In [315]:
#16
# Which Female employees’ preferred Language is English? 

lang = df[['Name','Gender','Preferred Language']]
lang = lang.loc[df['Preferred Language'] == 'English']

lang = lang.loc[df['Gender'] == 'F']
print(lang['Name'])

5    Pooja
Name: Name, dtype: object
